import Image from "next/image";

export const metaData = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div>
      <div className="grid grid-cols-3 items-center justify-between w-full h-full ">
        <div className="">{children}</div>
        <div className="relative w-full h-full col-span-2">
          <Image
            src="/black.jpg"
            fill
            alt="Discover Learning"
            className="object-cover"
          />
          <div className="absolute inset-0 bg-gradient-to-b from-black/40 via-theme/40 to-black/60" />

          <div className="flex flex-col z-10 justify-center items-center w-full h-full text-center px-6">
            <h1 className="heading  font-bold text-white drop-shadow-2xl">
              Unlock Your Future
            </h1>
            <p className="subHeading  text-gray-300  max-w-2xl leading-relaxed drop-shadow-lg">
              Join thousands of students mastering skills that shape tomorrow.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
