export const metaData = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
      {" "}
      <div>
        <Header />
        {children}
      </div>
    </>
  );
}
