export const metaData = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <div>
      <Header />
      {children}
    </div>
  );
}
