import Header from "@/components/features/Header";

export const metaData = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function TeacherLayout({ children }) {
  return (
    <>
      <div>
        <Header />
        {children}
      </div>
    </>
  );
}
